api_add_member:
    path:       /member
    controller:  App\Application\Controller\MemberController::add
    methods:    POST

api_find_member:
    path: /member/{id}
    methods: GET
    controller: App\Application\Controller\MemberController::find